In [1]:
import xarray as xr
import numpy as np
import datetime 
import numpy as np
import mpmath as mp
import pandas as pd
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import copy
from sklearn.preprocessing import StandardScaler
%matplotlib qt

from matplotlib.dates import DayLocator, HourLocator, DateFormatter, drange
import os 
from os import listdir
from os.path import isfile, join

def get_directory(folder):
    files= [a for a in listdir(folder) if isfile(join(folder,a))]
    
    return files
import os 
from os import listdir
from os.path import isfile, join

## DATA COD

In [2]:
data_folder="C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla"
#data_folder="C:/Users/enclab01/Desktop/THESIS/codigos tesis/dataseptiembre2"
list_of_files=get_directory(data_folder)

#List with the paths
newlist=[]
for item in list_of_files:
    newlist.append(data_folder+'/'+str(item))
print(newlist)

import GOES

MM_final_table=[]
for item in newlist:
    #Importing data
    titles=['Dates_and_Hours', 'COD','DQF']
    data= pd.read_table(str(item), header=None, names=titles, sep='\t')
    data2=data.iloc[np.arange(1,len(data)),:] #delete the first row
    data2=data2.reset_index(drop=True)
    MM_final_table.append(data2)

    
'merge the dataframes'
df1=MM_final_table[0]
for i in np.arange(1,len(MM_final_table)):
    df1=pd.concat([df1, MM_final_table[i]])
df1= df1.reset_index() 


print(df1)
df1['COD']=df1['COD'].astype(float)
df1['DQF']=df1['DQF'].astype(float)
'Reemplazar los valores que sean mayores a 50 por nans'
df1['COD'] = df1['COD'].apply(lambda x: np.nan if x > 50 else x)    
 
print(df1)    

'Drop the nans'
check_for_nan_1 = df1['COD'].isnull()
data_copy = df1.copy()
for i in np.arange(0,len(df1)):
    if check_for_nan_1[i]==True:
        data_copy.drop(i, axis=0, inplace=True)
df1=data_copy
df1= df1.reset_index() 

print(df1)
df1=df1[['Dates_and_Hours','COD' ,'DQF']]
# Ordenar en orden ascendente por la columna 'fecha'
df1 = df1.sort_values(by='Dates_and_Hours', ascending=True)  


print(df1)

'Rolling average'
df1['Rolling']=df1['COD'].rolling(10,center=True).mean()    
print('rolling',df1['Rolling'])

'1 minute resample'
#Resample
df1['index'] = pd.to_datetime(df1['Dates_and_Hours'])
df1.set_index('index', inplace=True)
df1=df1.resample('1T').mean()
df1['t_utc'] = pd.to_datetime(df1.index.values)
df1= df1.reset_index()

print(df1)
# Ordenar en orden ascendente por la columna 'fecha'
df1 = df1.sort_values(by='t_utc', ascending=True)
  

   
print(df1)
 
# -----------------------------------------------------------------    
'Veamos que pasa con un interpolate'    
    
time2=pd.to_datetime(df1['t_utc'])
# Interpolar los valores NaN en el DataFrame df
df2 = df1['COD'].interpolate(method='linear')
print(df2)    
COD_values2=df2
COD_values2=COD_values2.astype(float)  

df3 = df1['Rolling'].interpolate(method='linear')
print(df3)    
COD_values3=df3
COD_values3=COD_values3.astype(float)  


# -----------------------------------------------------------------    
    
'Drop the nans'
check_for_nan_1 = df1['COD'].isnull()
data_copy = df1.copy()
for i in np.arange(0,len(df1)):
    if check_for_nan_1[i]==True:
        data_copy.drop(i, axis=0, inplace=True)
df1=data_copy
df1= df1.reset_index() 

print(df1)    

time=pd.to_datetime(df1['t_utc'])
COD_values=df1['COD']
DQF_values=df1['DQF']

['C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/10Mes010.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/11Mes11.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/12Mes12.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/1Mes01.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/2Mes02.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/3Mes03.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/4Mes04.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/5Mes05.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/6Mes06.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/7Mes07.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/8Mes08.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/9Mes09.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes01.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes010.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes02.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes03.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes04.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes05.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes06.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes07.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes08.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes09.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes11.txt', 'C:/Users/enclab01/Desktop/THESIS/codigos tesis/eventos en la jolla/Mes12.txt']
      index             Dates_and_Hours        COD   DQF
0         0  2021-04-08 00:01:17.720737   7.215017   0.0
1         1  2021-04-08 00:06:17.720596  2.1022434   0.0
2         2  2021-04-08 00:11:17.722253  2.2072334   4.0
3         3  2021-04-08 00:16:17.722107        NaN  16.0
4         4  2021-04-08 00:21:17.721957   1.464978   4.0
...     ...                         ...        ...   ...
5550    211  2021-04-16 23:36:17.706701        NaN   6.0
5551    212  2021-04-16 23:41:17.706530        NaN   6.0
5552    213  2021-04-16 23:46:17.706353        NaN   6.0
5553    214  2021-04-16 23:51:17.706179        NaN   6.0
5554    215  2021-04-16 23:56:17.707807        NaN   6.0

[5555 rows x 4 columns]
      index             Dates_and_Hours       COD   DQF
0         0  2021-04-08 00:01:17.720737  7.215017   0.0
1         1  2021-04-08 00:06:17.720596  2.102243   0.0
2         2  2021-04-08 00:11:17.722253  2.207233   4.0
3         3  2021-04-08 00:16:17.722107       NaN  16.0
4         4  2021-04-08 00:21:17.721957  1.464978   4.0
...     ...                         ...       ...   ...
5550    211  2021-04-16 23:36:17.706701       NaN   6.0
5551    212  2021-04-16 23:41:17.706530       NaN   6.0
5552    213  2021-04-16 23:46:17.706353       NaN   6.0
5553    214  2021-04-16 23:51:17.706179       NaN   6.0
5554    215  2021-04-16 23:56:17.707807       NaN   6.0

[5555 rows x 4 columns]
      level_0  index             Dates_and_Hours       COD  DQF
0           0      0  2021-04-08 00:01:17.720737  7.215017  0.0
1           1      1  2021-04-08 00:06:17.720596  2.102243  0.0
2           2      2  2021-04-08 00:11:17.722253  2.207233  4.0
3           4      4  2021-04-08 00:21:17.721957  1.464978  4.0
4           7      7  2021-04-08 00:36:17.721436  3.357241  4.0
...       ...    ...                         ...       ...  ...
1815     5462    123  2021-04-16 16:16:17.675747  5.828171  0.0
1816     5463    124  2021-04-16 16:21:17.675745  9.388067  0.0
1817     5464    125  2021-04-16 16:26:17.675742  6.685183  0.0
1818     5465    126  2021-04-16 16:31:17.675746  6.777965  0.0
1819     5474    135  2021-04-16 17:16:17.679593  2.688235  0.0

[1820 rows x 5 columns]
                 Dates_and_Hours        COD  DQF
176   2021-01-26 00:01:17.707871   5.002900  4.0
177   2021-01-26 00:06:17.707819   9.451550  4.0
178   2021-01-26 00:11:17.707769   5.718298  4.0
179   2021-01-26 00:16:17.707722  11.202198  4.0
180   2021-01-26 00:31:17.709405   0.578666  5.0
...                          ...        ...  ...
1815  2021-04-16 16:16:17.675747   5.828171  0.0
1816  2021-04-16 16:21:17.675745   9.388067  0.0
1817  2021-04-16 16:26:17.675742   6.685183  0.0
1818  2021-04-16 16:31:17.675746   6.777965  0.0
1819  2021-04-16 17:16:17.679593   2.688235  0.0

[1820 rows x 3 columns]
rolling 176          NaN
177          NaN
178          NaN
179          NaN
180          NaN
          ...
1815    9.126325
1816         NaN
1817         NaN
1818         NaN
1819         NaN
Name: Rolling, Length: 1820, dtype: float64
                     index       COD  DQF  Rolling               t_utc
0      2021-01-26 00:01:00  5.002900  4.0      NaN 2021-01-26 00:01:00
1      2021-01-26 00:02:00       NaN  NaN      NaN 2021-01-26 00:02:00
2      2021-01-26 00:03:00       NaN  NaN      NaN 2021-01-26 00:03:00
3      2021-01-26 00:04:00       NaN  NaN      NaN 2021-01-26 00:04:00
4      2021-01-26 00:05:00       NaN  NaN      NaN 2021-01-26 00:05:00
...                    ...       ...  ...      ...                 ...
116231 2021-04-16 17:12:00       NaN  NaN      NaN 2021-04-16 17:12:00
116232 2021-04-16 17:13:00       NaN  NaN      NaN 2021-04-16 17:13:00
116233 2021-04-16 17:14:00       NaN  NaN      NaN 2021-04-16 17:14:00
116234 2021-04-16 17:15:00       NaN  NaN      NaN 2021-04-16 17:15:00
116235 2021-04-16 17:16:00  2.688235  0.0      NaN 2021-04-16 17:16:00

[116236 rows x 5 columns]
                     index       COD  DQF  Rolling               t_utc
0      2021-01-26 00:01:00  5.002900  4.0      NaN 2021-01-26 00:01:00
1      2021-01-26 00:02:00       NaN  NaN      NaN 2021-01-26 00:02:00
2      2021-01-26 00:03:00       NaN  NaN      NaN 2021-01-26 00:03:00
3      2021-01-26 00:04:00       NaN  NaN      NaN 2021-01-26 00:04:00
4      2021-01-26 00:05:00       NaN  NaN      NaN 2021-01-26 00:05:00
...                    ...       ...  ...      ...                 ...
116231 2021-04-16 17:12:00       NaN  NaN      NaN 2021-04-16 17:12:00
116232 2021-04-16 17:13:00       NaN  NaN      NaN 2021-04-16 17:13:00
116233 2021-04-16 17:14:00       NaN  NaN      NaN 2021-04-16 17:14:00
116234 2021-04-16 17:15:00       NaN  NaN      NaN 2021-04-16 17:15:00
116235 2021-04-16 17:16:00  2.688235  0.0      NaN 2021-04-16 17:16:00

[116236 rows x 5 columns]
0         5.002900
1         5.892630
2         6.782360
3         7.672090
4         8.561820
            ...
116231    3.051766
116232    2.960883
116233    2.870000
116234    2.779117
116235    2.688235
Name: COD, Length: 116236, dtype: float64
0              NaN
1              NaN
2              NaN
3              NaN
4              NaN
            ...
116231    9.126325
116232    9.126325
116233    9.126325
116234    9.126325
116235    9.126325
Name: Rolling, Length: 116236, dtype: float64
      level_0               index        COD  DQF   Rolling  \
0           0 2021-01-26 00:01:00   5.002900  4.0       NaN
1           5 2021-01-26 00:06:00   9.451550  4.0       NaN
2          10 2021-01-26 00:11:00   5.718298  4.0       NaN
3          15 2021-01-26 00:16:00  11.202198  4.0       NaN
4          30 2021-01-26 00:31:00   0.578666  5.0       NaN
...       ...                 ...        ...  ...       ...
1746   116175 2021-04-16 16:16:00   5.828171  0.0  9.126325
1747   116180 2021-04-16 16:21:00   9.388067  0.0       NaN
1748   116185 2021-04-16 16:26:00   6.685183  0.0       NaN
1749   116190 2021-04-16 16:31:00   6.777965  0.0       NaN
1750   116235 2021-04-16 17:16:00   2.688235  0.0       NaN

                   t_utc
0    2021-01-26 00:01:00
1    2021-01-26 00:06:00
2    2021-01-26 00:11:00
3    2021-01-26 00:16:00
4    2021-01-26 00:31:00
...                  ...
1746 2021-04-16 16:16:00
1747 2021-04-16 16:21:00
1748 2021-04-16 16:26:00
1749 2021-04-16 16:31:00
1750 2021-04-16 17:16:00

[1751 rows x 6 columns]

### Visualize the events

In [3]:
"Insert the date of interest"

"event 1"
#fecha_inicio = pd.to_datetime('2021-01-27 08:35:00')
#fecha_fin = pd.to_datetime(' 2021-01-27 11:20:00')
fecha_inicio1 = pd.to_datetime('2021-01-27 00:35:00')
fecha_fin1 = pd.to_datetime(' 2021-01-27 03:20:00')

#

"event 2" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-02-04 07:40:00')
#fecha_fin = pd.to_datetime(' 2021-02-04 12:20:00')
fecha_inicio2 = pd.to_datetime('2021-02-03 23:40:00')
fecha_fin2 = pd.to_datetime(' 2021-02-04 04:20:00')

#

"event 3" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-02-17 07:30:00')
#fecha_fin = pd.to_datetime(' 2021-02-17 10:50:00')
fecha_inicio3 = pd.to_datetime('2021-02-16 23:30:00')
fecha_fin3 = pd.to_datetime(' 2021-02-17 02:50:00')

#

"event 4"
#fecha_inicio = pd.to_datetime('2021-03-04 09:30:00 ')
#fecha_fin = pd.to_datetime('  2021-03-04 11:10:00')
fecha_inicio4 = pd.to_datetime('2021-03-04 01:30:00 ')
fecha_fin4 = pd.to_datetime('  2021-03-04 03:10:00')

#

"event 5" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-03-11 06:30:00 ')
#fecha_fin = pd.to_datetime('   2021-03-11 11:00:00')
fecha_inicio5 = pd.to_datetime('2021-03-10 22:30:00 ')
fecha_fin5 = pd.to_datetime('   2021-03-11 03:00:00')

#

"event 6" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-03-16 07:05:00')
#fecha_fin = pd.to_datetime('   2021-03-16 10:50:00')
fecha_inicio6 = pd.to_datetime('2021-03-15 23:05:00')
fecha_fin6 = pd.to_datetime('   2021-03-16 02:50:00')

#

"event 7" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-03-20 06:25:00 ')
#fecha_fin = pd.to_datetime('   2021-03-20 12:20:00')
fecha_inicio7 = pd.to_datetime('2021-03-19 22:25:00')
fecha_fin7 = pd.to_datetime('2021-03-20 04:20:00')

#

"event 8" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-03-21 07:50:00')
#fecha_fin = pd.to_datetime(' 2021-03-21 11:15:00')
fecha_inicio8 = pd.to_datetime('2021-03-20 23:50:00')
fecha_fin8 = pd.to_datetime(' 2021-03-21 03:15:00')

#

"event 9" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-04-03 06:35:00 ')
#fecha_fin = pd.to_datetime('2021-04-03 10:05:00')
fecha_inicio9 = pd.to_datetime('2021-04-02 22:35:00')
fecha_fin9 = pd.to_datetime('2021-04-03 02:05:00')

#

"event 10" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-04-09 05:45:00 ')
#fecha_fin = pd.to_datetime('2021-04-09 08:35:00')
fecha_inicio10 = pd.to_datetime('2021-04-08 21:45:00 ')
fecha_fin10 = pd.to_datetime('2021-04-09 00:35:00')

#

"event 11" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-04-10 05:35:00')
#fecha_fin = pd.to_datetime('2021-04-10 09:05:00')
fecha_inicio11 = pd.to_datetime('2021-04-09 21:35:00')
fecha_fin11 = pd.to_datetime('2021-04-10 01:05:00')

#

"event 12" "faltan datos para atras"
#fecha_inicio = pd.to_datetime('2021-04-16 06:45:00 ')
#fecha_fin = pd.to_datetime('2021-04-16 09:35:00')
fecha_inicio12 = pd.to_datetime('2021-04-15 22:45:00 ')
fecha_fin12 = pd.to_datetime('2021-04-16 01:35:00')

#

fechas_de_inicio=[fecha_inicio1,fecha_inicio2,fecha_inicio3,fecha_inicio4,fecha_inicio5,fecha_inicio6,fecha_inicio7,fecha_inicio8,fecha_inicio9,fecha_inicio10,fecha_inicio11,fecha_inicio12]
fechas_de_fin=[fecha_fin1,fecha_fin2,fecha_fin3,fecha_fin4,fecha_fin5,fecha_fin6,fecha_fin7,fecha_fin8,fecha_fin9,fecha_fin10,fecha_fin11,fecha_fin12]


for i in np.arange(0,len(fechas_de_inicio)):
    
    df1_filtrado = df1[(df1['t_utc'] >= fechas_de_inicio[i]) & (df1['t_utc'] <= fechas_de_fin[i])]
    print(df1_filtrado)
    

    fig, ax = plt.subplots(1)
    fig.autofmt_xdate()

    plt.plot(df1_filtrado['t_utc'], df1_filtrado['COD'],'-x',c='black')


    #plt.plot(time, derivative,'-.',c='red') 
    #plt.plot(time, rolling,'X',c='black') 

    plt.ylabel('COD Measurements')
    plt.xlabel('Time (UTC)')
    xfmt = mdates.DateFormatter('%b %d %H:%M')
    ax.xaxis.set_major_formatter(xfmt)

     level_0               index       COD  DQF   Rolling               t_utc
169     1570 2021-01-27 02:11:00  0.441935  1.0  6.504502 2021-01-27 02:11:00
     level_0               index        COD  DQF    Rolling  \
327    12960 2021-02-04 00:01:00  14.940334  4.0  15.519489
328    12965 2021-02-04 00:06:00  14.168778  4.0  14.229576
329    12970 2021-02-04 00:11:00  16.625060  4.0  13.337892
330    12975 2021-02-04 00:16:00  16.100110  4.0  12.452802
331    12980 2021-02-04 00:21:00  22.143143  4.0  11.067665
332    12985 2021-02-04 00:26:00   4.001831  4.0  10.100779
333    12990 2021-02-04 00:31:00   6.311614  4.0   8.637266
334    12995 2021-02-04 00:36:00   5.972227  4.0   7.307555
335    13005 2021-02-04 00:46:00   0.336945  5.0   5.740028
336    13020 2021-02-04 01:01:00   0.407752  5.0   4.208149
337    13025 2021-02-04 01:06:00   0.305204  5.0   2.078804
338    13030 2021-02-04 01:11:00   0.871662  5.0   1.714513
339    13035 2021-02-04 01:16:00   0.949794  5.0   1.120220
340    13040 2021-02-04 01:21:00   0.781322  1.0   0.561575
341    13045 2021-02-04 01:26:00   0.849687  1.0   0.566702
342    13050 2021-02-04 01:31:00   0.358920  1.0   0.595514
343    13055 2021-02-04 01:36:00   0.368686  1.0   0.625057
344    13060 2021-02-04 01:41:00   0.385778  1.0   0.645323
345    13065 2021-02-04 01:46:00   0.388219  1.0   0.651183
346    13070 2021-02-04 01:51:00   0.695865  1.0   0.691225
347    13075 2021-02-04 01:56:00   0.600641  1.0   0.761056
348    13080 2021-02-04 02:01:00   1.074317  1.0   0.898764
349    13085 2021-02-04 02:06:00   1.008393  1.0   1.054296
350    13090 2021-02-04 02:11:00   1.181749  1.0   1.121929
351    13095 2021-02-04 02:16:00   1.547993  1.0   1.247673
352    13100 2021-02-04 02:21:00   1.735999  1.0   1.315306
353    13105 2021-02-04 02:26:00   1.924004  1.0   1.353884
354    13110 2021-02-04 02:31:00   1.062109  1.0   1.355593
355    13115 2021-02-04 02:36:00   1.645659  1.0   1.358523
356    13120 2021-02-04 02:41:00   1.372196  1.0   1.317748
357    13125 2021-02-04 02:46:00   0.986419  1.0   1.235953
358    13130 2021-02-04 02:51:00   1.091409  1.0   1.118267
359    13135 2021-02-04 02:56:00   1.037693  1.0   0.953212
360    13140 2021-02-04 03:01:00   0.773997  1.0   0.927575
361    13145 2021-02-04 03:06:00   0.730047  1.0   0.817214
362    13150 2021-02-04 03:11:00   0.559133  1.0   0.741035
363    13155 2021-02-04 03:16:00   0.273463  1.0   0.676332
364    13160 2021-02-04 03:21:00   0.805738  1.0   0.615535
365    13165 2021-02-04 03:26:00   0.542042  1.0   0.563772
366    13170 2021-02-04 03:31:00   0.610407  1.0   0.549611
367    13175 2021-02-04 03:36:00   0.339387  1.0   0.528369
368    13180 2021-02-04 03:41:00   0.483443  1.0   0.507859
369    13185 2021-02-04 03:46:00   0.520067  1.0   0.505173
370    13190 2021-02-04 03:51:00   0.632382  1.0   0.463421
371    13195 2021-02-04 03:56:00   0.517626  1.0   0.438273
372    13200 2021-02-04 04:01:00   0.354036  1.0   0.389196
373    13205 2021-02-04 04:06:00   0.246605  1.0   0.368198
374    13210 2021-02-04 04:11:00   0.388219  1.0   0.362094
375    13215 2021-02-04 04:16:00   0.290554  1.0   0.320830

                  t_utc
327 2021-02-04 00:01:00
328 2021-02-04 00:06:00
329 2021-02-04 00:11:00
330 2021-02-04 00:16:00
331 2021-02-04 00:21:00
332 2021-02-04 00:26:00
333 2021-02-04 00:31:00
334 2021-02-04 00:36:00
335 2021-02-04 00:46:00
336 2021-02-04 01:01:00
337 2021-02-04 01:06:00
338 2021-02-04 01:11:00
339 2021-02-04 01:16:00
340 2021-02-04 01:21:00
341 2021-02-04 01:26:00
342 2021-02-04 01:31:00
343 2021-02-04 01:36:00
344 2021-02-04 01:41:00
345 2021-02-04 01:46:00
346 2021-02-04 01:51:00
347 2021-02-04 01:56:00
348 2021-02-04 02:01:00
349 2021-02-04 02:06:00
350 2021-02-04 02:11:00
351 2021-02-04 02:16:00
352 2021-02-04 02:21:00
353 2021-02-04 02:26:00
354 2021-02-04 02:31:00
355 2021-02-04 02:36:00
356 2021-02-04 02:41:00
357 2021-02-04 02:46:00
358 2021-02-04 02:51:00
359 2021-02-04 02:56:00
360 2021-02-04 03:01:00
361 2021-02-04 03:06:00
362 2021-02-04 03:11:00
363 2021-02-04 03:16:00
364 2021-02-04 03:21:00
365 2021-02-04 03:26:00
366 2021-02-04 03:31:00
367 2021-02-04 03:36:00
368 2021-02-04 03:41:00
369 2021-02-04 03:46:00
370 2021-02-04 03:51:00
371 2021-02-04 03:56:00
372 2021-02-04 04:01:00
373 2021-02-04 04:06:00
374 2021-02-04 04:11:00
375 2021-02-04 04:16:00
     level_0               index       COD  DQF   Rolling               t_utc
631    31650 2021-02-16 23:31:00  2.300015  4.0  2.483382 2021-02-16 23:31:00
632    31655 2021-02-16 23:36:00  2.160843  4.0  2.493637 2021-02-16 23:36:00
633    31660 2021-02-16 23:41:00  2.019228  4.0  2.391821 2021-02-16 23:41:00
634    31665 2021-02-16 23:46:00  2.446513  4.0  2.324432 2021-02-16 23:46:00
635    31670 2021-02-16 23:51:00  2.141310  4.0  2.546376 2021-02-16 23:51:00
636    31675 2021-02-16 23:56:00  2.285366  4.0  2.987090 2021-02-16 23:56:00
637    31680 2021-02-17 00:01:00  1.655425  4.0  3.329895 2021-02-17 00:01:00
638    31685 2021-02-17 00:06:00  2.832291  4.0  3.513994 2021-02-17 00:06:00
639    31690 2021-02-17 00:11:00  4.714787  4.0  3.741310 2021-02-17 00:11:00
640    31695 2021-02-17 00:16:00  7.315124  4.0  4.041386 2021-02-17 00:16:00
641    31700 2021-02-17 00:21:00  5.728064  4.0  4.715764 2021-02-17 00:21:00
642    31705 2021-02-17 00:26:00  4.001831  4.0  4.542409 2021-02-17 00:26:00
643    31710 2021-02-17 00:31:00  4.292386  4.0  4.412025 2021-02-17 00:31:00
644    31715 2021-02-17 00:36:00  5.447277  4.0  4.152969 2021-02-17 00:36:00
645    31725 2021-02-17 00:46:00  8.885092  4.0  3.707127 2021-02-17 00:46:00
646    31730 2021-02-17 00:51:00  0.551808  5.0  3.016878 2021-02-17 00:51:00
647    31735 2021-02-17 00:56:00  0.351595  5.0  2.509507 2021-02-17 00:56:00
648    31745 2021-02-17 01:06:00  0.241721  5.0  2.182817 2021-02-17 01:06:00
649    31755 2021-02-17 01:16:00  0.256371  5.0  1.815352 2021-02-17 01:16:00
650    31760 2021-02-17 01:21:00  0.412635  5.0  1.321899 2021-02-17 01:21:00
651    31765 2021-02-17 01:26:00  0.654357  5.0  0.743232 2021-02-17 01:26:00
652    31770 2021-02-17 01:31:00  0.734931  1.0  0.869953 2021-02-17 01:31:00
653    31775 2021-02-17 01:36:00  0.617732  1.0  1.287227 2021-02-17 01:36:00
654    31780 2021-02-17 01:41:00  0.512742  1.0  1.705478 2021-02-17 01:41:00
     level_0               index       COD  DQF    Rolling               t_utc
706    53380 2021-03-04 01:41:00  1.826339  5.0  15.589563 2021-03-04 01:41:00
707    53385 2021-03-04 01:46:00  3.042271  1.0  11.712499 2021-03-04 01:46:00
708    53390 2021-03-04 01:51:00  2.595453  1.0   9.751626 2021-03-04 01:51:00
709    53400 2021-03-04 02:01:00  3.999390  1.0   7.054113 2021-03-04 02:01:00
710    53405 2021-03-04 02:06:00  2.988555  1.0   2.983428 2021-03-04 02:06:00
711    53410 2021-03-04 02:11:00  4.023806  1.0   4.107310 2021-03-04 02:11:00
712    53415 2021-03-04 02:16:00  2.751717  1.0   4.142714 2021-03-04 02:16:00
713    53420 2021-03-04 02:21:00  2.158401  1.0   4.205952 2021-03-04 02:21:00
714    53425 2021-03-04 02:26:00  1.687166  1.0   4.310209 2021-03-04 02:26:00
     level_0               index        COD  DQF    Rolling  \
858    63270 2021-03-10 22:31:00  11.946896  0.0  14.151688
859    63275 2021-03-10 22:36:00  17.648102  0.0  13.986145
860    63280 2021-03-10 22:41:00  46.312840  0.0  13.387702
861    63285 2021-03-10 22:46:00   7.078285  0.0  13.498307
862    63290 2021-03-10 22:51:00  16.036625  0.0  13.452405
863    63295 2021-03-10 22:56:00   7.127118  0.0  13.118390
864    63315 2021-03-10 23:16:00   2.553945  0.0  13.523700
865    63400 2021-03-11 00:41:00  12.386389  4.0  11.875600
866    63425 2021-03-11 01:06:00   7.166184  4.0   7.331238
867    63490 2021-03-11 02:11:00   2.927514  1.0   6.691775
868    63495 2021-03-11 02:16:00  16.000002  1.0   5.150619
869    63500 2021-03-11 02:21:00   1.167099  1.0   4.567069
870    63505 2021-03-11 02:26:00   0.869220  1.0   4.615413
871    63510 2021-03-11 02:31:00   0.683656  1.0   4.976775
872    63515 2021-03-11 02:36:00   0.625057  1.0   4.602961
873    63520 2021-03-11 02:41:00   1.291622  1.0   4.331452
874    63525 2021-03-11 02:46:00   3.037388  1.0   2.771494
875    63530 2021-03-11 02:51:00  16.000002  1.0   2.655761
876    63535 2021-03-11 02:56:00   3.428049  1.0   2.588128

                  t_utc
858 2021-03-10 22:31:00
859 2021-03-10 22:36:00
860 2021-03-10 22:41:00
861 2021-03-10 22:46:00
862 2021-03-10 22:51:00
863 2021-03-10 22:56:00
864 2021-03-10 23:16:00
865 2021-03-11 00:41:00
866 2021-03-11 01:06:00
867 2021-03-11 02:11:00
868 2021-03-11 02:16:00
869 2021-03-11 02:21:00
870 2021-03-11 02:26:00
871 2021-03-11 02:31:00
872 2021-03-11 02:36:00
873 2021-03-11 02:41:00
874 2021-03-11 02:46:00
875 2021-03-11 02:51:00
876 2021-03-11 02:56:00
      level_0               index        COD  DQF   Rolling  \
1244    70505 2021-03-15 23:06:00   3.440257  0.0  8.236106
1245    70510 2021-03-15 23:11:00   8.523730  0.0  8.101572
1246    70515 2021-03-15 23:16:00   4.849077  0.0  8.257104
1247    70525 2021-03-15 23:26:00   3.457348  0.0  5.823532
1248    70530 2021-03-15 23:31:00   6.550893  0.0  6.624630
1249    70535 2021-03-15 23:36:00   5.955135  0.0  6.225668
1250    70545 2021-03-15 23:46:00   7.266291  0.0  6.524524
1251    70550 2021-03-15 23:51:00   5.161606  4.0  6.707402
1252    70555 2021-03-15 23:56:00  14.083322  4.0  6.892233
1253    70570 2021-03-16 00:11:00   2.969022  4.0  7.547078
1254    70575 2021-03-16 00:16:00   6.428812  4.0  8.491989
1255    70605 2021-03-16 00:46:00  10.352511  4.0  7.938472
1256    70610 2021-03-16 00:51:00   6.697391  4.0  7.708958
1257    70625 2021-03-16 01:06:00  10.005799  4.0  7.351748
1258    70635 2021-03-16 01:16:00  16.000002  5.0  7.543416
1259    70640 2021-03-16 01:21:00   0.419960  5.0  7.333192
1260    70645 2021-03-16 01:26:00   4.971158  5.0  6.903465
1261    70650 2021-03-16 01:31:00   1.589501  5.0  5.970274
1262    70660 2021-03-16 01:41:00  16.000002  5.0  5.361087
1263    70665 2021-03-16 01:46:00   0.866779  5.0  5.960507
1264    70680 2021-03-16 02:01:00   2.131543  1.0  4.505784
1265    70685 2021-03-16 02:06:00   1.020601  1.0  4.567557
1266    70720 2021-03-16 02:41:00   0.605524  1.0  5.670442
1267    70725 2021-03-16 02:46:00  16.000002  1.0  5.731727

                   t_utc
1244 2021-03-15 23:06:00
1245 2021-03-15 23:11:00
1246 2021-03-15 23:16:00
1247 2021-03-15 23:26:00
1248 2021-03-15 23:31:00
1249 2021-03-15 23:36:00
1250 2021-03-15 23:46:00
1251 2021-03-15 23:51:00
1252 2021-03-15 23:56:00
1253 2021-03-16 00:11:00
1254 2021-03-16 00:16:00
1255 2021-03-16 00:46:00
1256 2021-03-16 00:51:00
1257 2021-03-16 01:06:00
1258 2021-03-16 01:16:00
1259 2021-03-16 01:21:00
1260 2021-03-16 01:26:00
1261 2021-03-16 01:31:00
1262 2021-03-16 01:41:00
1263 2021-03-16 01:46:00
1264 2021-03-16 02:01:00
1265 2021-03-16 02:06:00
1266 2021-03-16 02:41:00
1267 2021-03-16 02:46:00
Empty DataFrame
Columns: [level_0, index, COD, DQF, Rolling, t_utc]
Index: []
      level_0               index       COD  DQF   Rolling               t_utc
1365    77815 2021-03-21 00:56:00  5.256829  4.0  6.849504 2021-03-21 00:56:00
Empty DataFrame
Columns: [level_0, index, COD, DQF, Rolling, t_utc]
Index: []
      level_0               index       COD  DQF   Rolling               t_utc
1466   105035 2021-04-08 22:36:00  2.998321  0.0  2.138135 2021-04-08 22:36:00
1467   105040 2021-04-08 22:41:00  2.917748  0.0  2.278041 2021-04-08 22:41:00
1468   105045 2021-04-08 22:46:00  2.832291  0.0  2.311247 2021-04-08 22:46:00
1469   105050 2021-04-08 22:51:00  2.727301  0.0  2.346406 2021-04-08 22:51:00
1470   105055 2021-04-08 22:56:00  2.751717  0.0  2.204792 2021-04-08 22:56:00
1471   105060 2021-04-08 23:01:00  2.578361  0.0  2.060980 2021-04-08 23:01:00
1472   105140 2021-04-09 00:21:00  1.814131  4.0  1.625149 2021-04-09 00:21:00
      level_0               index       COD  DQF   Rolling               t_utc
1524   106415 2021-04-09 21:36:00  2.348848  0.0  2.457501 2021-04-09 21:36:00
1525   106460 2021-04-09 22:21:00  1.941096  0.0  2.381200 2021-04-09 22:21:00
1526   106465 2021-04-09 22:26:00  2.143751  0.0  2.136060 2021-04-09 22:26:00
1527   106475 2021-04-09 22:36:00  1.892263  0.0  1.986022 2021-04-09 22:36:00
1528   106480 2021-04-09 22:41:00  1.985045  0.0  1.932794 2021-04-09 22:41:00
1529   106495 2021-04-09 22:56:00  1.840989  0.0  1.875172 2021-04-09 22:56:00
1530   106500 2021-04-09 23:01:00  1.755532  0.0  1.832687 2021-04-09 23:01:00
1531   106505 2021-04-09 23:06:00  1.821456  0.0  1.799725 2021-04-09 23:06:00
1532   106510 2021-04-09 23:11:00  1.716466  0.0  1.795697 2021-04-09 23:11:00
1533   106515 2021-04-09 23:16:00  1.823898  0.0  2.155593 2021-04-09 23:16:00
1534   106535 2021-04-09 23:36:00  1.867847  0.0  2.668457 2021-04-09 23:36:00
      level_0               index        COD  DQF   Rolling  \
1636   115200 2021-04-16 00:01:00   3.630704  0.0  2.595209
1637   115205 2021-04-16 00:06:00   3.442698  0.0  3.113322
1638   115210 2021-04-16 00:11:00   3.869983  0.0  3.417550
1639   115215 2021-04-16 00:16:00   4.580498  4.0  3.569663
1640   115220 2021-04-16 00:21:00   4.145888  4.0  4.140272
1641   115225 2021-04-16 00:26:00   6.262781  4.0  4.341951
1642   115230 2021-04-16 00:31:00   4.302152  4.0  4.402015
1643   115235 2021-04-16 00:36:00   2.859149  4.0  4.243309
1644   115240 2021-04-16 00:41:00   7.048986  4.0  4.111949
1645   115245 2021-04-16 00:46:00   3.276667  4.0  4.182024
1646   115250 2021-04-16 00:51:00   4.231345  4.0  4.167130
1647   115255 2021-04-16 00:56:00   1.855639  4.0  3.947872
1648   115260 2021-04-16 01:01:00   2.556387  4.0  4.865436
1649   115265 2021-04-16 01:06:00   5.281246  4.0  5.410652
1650   115270 2021-04-16 01:11:00   3.996948  4.0  5.258050
1651   115275 2021-04-16 01:16:00   4.070197  4.0  4.971403
1652   115280 2021-04-16 01:21:00  13.477797  4.0  4.583184
1653   115285 2021-04-16 01:26:00   8.311309  4.0  4.437907
1654   115290 2021-04-16 01:31:00   5.522967  4.0  4.214742

                   t_utc
1636 2021-04-16 00:01:00
1637 2021-04-16 00:06:00
1638 2021-04-16 00:11:00
1639 2021-04-16 00:16:00
1640 2021-04-16 00:21:00
1641 2021-04-16 00:26:00
1642 2021-04-16 00:31:00
1643 2021-04-16 00:36:00
1644 2021-04-16 00:41:00
1645 2021-04-16 00:46:00
1646 2021-04-16 00:51:00
1647 2021-04-16 00:56:00
1648 2021-04-16 01:01:00
1649 2021-04-16 01:06:00
1650 2021-04-16 01:11:00
1651 2021-04-16 01:16:00
1652 2021-04-16 01:21:00
1653 2021-04-16 01:26:00
1654 2021-04-16 01:31:00

In [4]:
d

NameError: name 'd' is not defined

## ALGORITHM

In [ ]:
from scipy.signal import find_peaks
from scipy.signal import find_peaks, savgol_filter


'PEAKS DATOS ORIGINALES'

indicess = find_peaks(COD_values, height=0.00002, prominence=(None, 4000), width=(0.000002, 4000),  rel_height=1)
index=indicess[0]

pir=[]
widths=[]
for m in np.arange(0,len(indicess[1]['peak_heights'])):
    pir.append([indicess[0][m],indicess[1]['prominences'][m],indicess[1]['peak_heights'][m],abs(indicess[1]['right_ips'][m]-indicess[1]['left_ips'][m])])
    widths.append(indicess[1]['widths'][m])    
    
'ROLLING AVERAGE'

#Transform a list into a data column
df = pd.DataFrame({'col':COD_values})
dqfvalues=df['col']
rolling=dqfvalues.rolling(10,center=True).mean()

#'peaks rolling'
#indicesrolling,properties = find_peaks(rolling,prominence=1,width=5,  rel_height=1)
    
    
'peaks rolling tras el resample'
indicesrolling, properties = find_peaks(COD_values3, prominence=1,width=5,  rel_height=1)
print(len(indicesrolling)) 
print(len(properties))

In [ ]:
import math
from datetime import datetime, timedelta


left=[]
right=[]
time_left=[]
time_right=[]
minutes=[]
for i in np.arange(0,len(indicesrolling)):
    left.append(math.floor(properties["left_ips"][i]))
    right.append(math.ceil(properties["right_ips"][i]))
    time_left.append(time2[math.floor(properties["left_ips"][i])])
    time_right.append(time2[math.ceil(properties["right_ips"][i])])
    
    diferencia= time2[math.ceil(properties["right_ips"][i])] - time2[math.floor(properties["left_ips"][i])] 
    minutos_diferencia = diferencia.total_seconds()/60
    minutes.append(minutos_diferencia)
    
    
#Create a dataframe with all the variables needed for the analysis 
dataframe = pd.DataFrame({'Time_left':time_left,'Time_right':time_right,'Left':left,'Right':right, 'Minutes': minutes, 'Prominences': properties["prominences"]})  
print(dataframe)

## Histogram

In [ ]:
plt.figure()
plt.hist(dataframe["Minutes"],bins=200,range=(0,3150))
plt.xlabel('Length of Cloud Dissipation (minutes)')
plt.ylabel('Count (nº Events)')

In [ ]:
plt.figure()
plt.hist(dataframe["Prominences"],bins=200,range=(0,30))
plt.xlabel('Delta COD')
plt.ylabel('Count (nº Events)')

## 2D HISTOGRAM

In [ ]:
x=dataframe["Minutes"]
xx=x.astype(float)
y=dataframe["Prominences"]
yy=y.astype(float)

xedges=50
yedges=50
xmin=0
xmax=600
ymin=0
ymax=10  

HHH, xedges, yedges= np.histogram2d(xx,yy, bins=(xedges,yedges), range=[[xmin,xmax],[ymin,ymax]])

extent = [xmin,xmax, ymin, ymax]

fig, ax= plt.subplots()

im=ax.imshow(HHH.T ,origin='lower', extent=extent, aspect='auto')
plt.colorbar(im, label='# Dissipation events per bin')
#plt.clim(0,0.001) #This limit shows how to low values looks like

#ax.set_facecolor((0.8,0.8,0.8))
ax.set_facecolor('grey')
plt.xlabel('Length of Cloud Dissipation (minutes)',fontsize=12)
plt.ylabel('COD variations', fontsize=12)

##  OTROS GRAFICOS

In [ ]:
from datetime import datetime, timedelta

# Definir dos objetos de fecha y hora
fecha1 = datetime(2023, 9, 11, 10, 30)  # Año, mes, día, hora, minutos
fecha2 = datetime(2023, 9, 11, 12, 45)

# Calcular la diferencia entre las dos fechas y obtener el resultado en minutos
diferencia = fecha2 - fecha1
minutos_diferencia = diferencia.total_seconds() / 60

print(minutos_diferencia)

In [ ]:
'----------------------------------------------------------------------------'
fig, ax = plt.subplots(1)
fig.autofmt_xdate()

plt.plot(time2, COD_values2,'-x',c='red')
plt.plot(time2, COD_values3,'-x',c='purple') 

plt.plot(time, COD_values,'-x',c='black') 
 
    
#plt.plot(time, derivative,'-.',c='red') 
#plt.plot(time, rolling,'X',c='black') 
 
plt.ylabel('COD Measurements')
plt.xlabel('Time (UTC)')
xfmt = mdates.DateFormatter('%b %d %H:%M')
ax.xaxis.set_major_formatter(xfmt)

In [ ]:
COD_values3

## NUEVO PLOT PARA VISUALIZAR LOS ANCHOS

In [ ]:
'----------------------------------------------------------------------------'
sas=np.arange(0,len(time2))
fig, ax = plt.subplots(1)

'Ploteamos el rolling average'
plt.plot( sas , COD_values3,'-x',c='black') 
 
    
plt.ylabel('COD Measurements')
plt.xlabel('Time (UTC)')

plt.vlines(x=sas[indicesrolling], ymin=COD_values3[indicesrolling] - properties["prominences"],
           ymax = COD_values3[indicesrolling], color = "C1")
plt.hlines(y=properties["width_heights"], xmin=properties["left_ips"],
           xmax=properties["right_ips"], color = "C1")

plt.plot(properties["left_ips"], properties["width_heights"],'X',c='red')
plt.plot(properties["right_ips"], properties["width_heights"],'X',c='blue')


# Plotea líneas verticales en cada punto
for i in range(len(left)):
    ax.vlines(left[i], ymin=COD_values3[left[i]], ymax=COD_values3[left[i]]+10, color='purple', linestyle='-', alpha=0.5)
# Plotea líneas verticales en cada punto
for i in range(len(right)):
    ax.vlines(right[i], ymin=COD_values3[right[i]], ymax=COD_values3[right[i]]+10, color='purple', linestyle='-', alpha=0.5)

In [ ]:
print(properties["prominences"])

In [ ]:
#FIRST PLOT
plt.figure()
ax2=plt.subplot(212)
figsize=(20,4)
   
plt.plot(time, COD_values,'-x',c='black')     
plt.plot(time, rolling,'-x',c='purple') 
#plt.text(0.01, 0.75, "D)", fontweight="bold", fontsize=13 ,transform=ax7.transAxes)
plt.ylabel('COD (adimensional)',fontsize=13)



#SECOND PLOT

ax1=plt.subplot(211,sharex=ax2)
figsize=(20,4)
plt.plot(time2,HT_values ,'-x',color='black')
plt.plot(time2,10000*np.ones(len(time2)))
plt.ylabel('Altitude (m)',fontsize=13)